/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class metpserver_FileCRCIndex */

#ifndef _Included_metpserver_FileCRCIndex
#define _Included_metpserver_FileCRCIndex
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     metpserver_FileCRCIndex
 * Method:    calculateFileCRC
 * Signature: (Ljava/lang/String;IJJ)[J
 */
JNIEXPORT jlongArray JNICALL Java_metpserver_FileCRCIndex_calculateFileCRC
  (JNIEnv *, jobject, jstring, jint, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
